//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blog_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string Aspnetusers_Id { get; set; }
        public string Title { get; set; }
        public string Briefing { get; set; }
        public string Textpost { get; set; }
        public byte[] Picture { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<System.DateTime> DateChange { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
